-- Create sources table if not exists
create table if not exists sources (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  url text not null unique,
  enabled boolean default true,
  type text default 'rss',
  "lastFetchStatus" text,
  "lastErrorMessage" text,
  "lastCheckTime" bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add columns if they don't exist (for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'sources' and column_name = 'lastFetchStatus') then
    alter table sources add column "lastFetchStatus" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'sources' and column_name = 'lastErrorMessage') then
    alter table sources add column "lastErrorMessage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'sources' and column_name = 'lastCheckTime') then
    alter table sources add column "lastCheckTime" bigint;
  end if;
end $$;

-- Enable RLS
alter table sources enable row level security;

-- Create policy to allow all operations for anon/authenticated (for demo purposes)
-- In production, you should restrict this.
drop policy if exists "Allow all operations for everyone" on sources;
create policy "Allow all operations for everyone" on sources for all using (true) with check (true);

-- Also ensure 'news' table exists and has policies
create table if not exists news (
  id bigint generated by default as identity primary key,
  "uniqueHash" text not null unique,
  title text not null,
  "originalTitle" text,
  url text not null,
  "sourceName" text,
  "publishedAt" bigint,
  "fetchedAt" bigint,
  content text,
  status text,
  summary text,
  sentiment text,
  tags text[],
  "qualityScore" numeric,
  language text,
  "isCryptoRelated" boolean,
  "coinTickers" text[],
  "topicCategory" text,
  "riskLevel" text,
  entities jsonb,
  "rewrittenTitle" text,
  "rewrittenContent" text,
  "rewriteTemplate" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table news enable row level security;
drop policy if exists "Allow all operations for everyone" on news;
create policy "Allow all operations for everyone" on news for all using (true) with check (true);
